/home/g15farris/.conda/envs/farris/lib/python3.9/site-packages/torchvision/io/image.py:13: UserWarning: Failed to load image Python extension: libtorch_cuda_cu.so: cannot open shared object file: No such file or directory
Traceback (most recent call last):
  File "/home/g15farris/AdsGO/PdAg_CO_H/H_coverage/Ag305Pd100_Hcoverage/coverage_EMT.py", line 96, in <module>
    atoms = read('../../bare_nps/xyz/Ag305Pd100.xyz')
  File "/home/g15farris/.conda/envs/farris/lib/python3.9/site-packages/ase/io/formats.py", line 729, in read
    format = format or filetype(filename, read=isinstance(filename, str))
  File "/home/g15farris/.conda/envs/farris/lib/python3.9/site-packages/ase/io/formats.py", line 920, in filetype
    fd = open_with_compression(filename, 'rb')
  File "/home/g15farris/.conda/envs/farris/lib/python3.9/site-packages/ase/io/formats.py", line 551, in open_with_compression
    return open(filename, mode)
FileNotFoundError: [Errno 2] No such file or directory: '../../bare_nps/xyz/Ag305Pd100.xyz'
/home/g15farris/.conda/envs/farris/lib/python3.9/site-packages/torchvision/io/image.py:13: UserWarning: Failed to load image Python extension: libtorch_cuda_cu.so: cannot open shared object file: No such file or directory
